### PR TITLE
v2.0.0: Add multi-part sending suppport

### PR DESCRIPTION
**Pull request by peterdemartini**
- **BREAKING CHANGES** to the `@terascope/file-asset-apis` package:
     - Improve typescript definitions to be defined on a per format basis
     - Some of the exported class names have changed
     - `format` is now required
     - Change to the file sender API to support this new way
- **BREAKING CHANGES** to the asset bundle:
     - `format` is now required
     - `format` will dictate the file extension so it can be read appropriately
- Adds `ChunkGenerator` that will allow a more streamable chunk solution
- Uploads to s3 now the multi-part file uploads if there are multiple chunks.
- Fix issue where defaults were not applied correctly
- When `file_per_slice` is true, the file sender will now remove any existing file before appending to avoid creating invalid formatted files.

### CODE REVIEW

**Comment by peterdemartini** [comment]
This is done, we are running through the manual tests

**Comment by peterdemartini** [comment]
Looks @jsnoble found some asset validation issues

**Comment by peterdemartini** [comment]
Alright this appears to work after manually test

**Review by jsnoble — APPROVED** [review]
LGTM

**Pull request merged**
